### ISSUE TITLE
furnace addition

### ISSUE THREAD

**Issue by BraunthePirate** [Aiidoneus/The-Ascent-RPG-Modpack-Issues#31] opened 2019-06-07 05:11 UTC
Please add https://minecraft.curseforge.com/projects/furnace-overhaul?gameCategorySlug=mc-mods&projectID=262742

Would add nothing to crazy in terms of furnaces, keeping it fairly vanilla just the upgrades alone make smelting more effective.

**Comment by Aiidoneus** [comment] 2019-06-07 22:34
Duplicate of #13

**Closed by Aiidoneus** 2019-06-07 22:34 UTC
Labels: duplicate
